export default [
  {
      data:{
          id:1,
          name:'雷军',
          nodeType:1,//0:人员，1:企业
          related:true,
      }
  },
  {
      data:{
          id:2,
          name:'小米之家',
          nodeType:2,//0:人员，1:企业
          related:true,
      }
  },
  {
      data:{
          id:3,
          name:'珠海金山',
          nodeType:2,//0:人员，1:企业
          related:true,
      }
  },
  {
      data:{
          id:4,
          name:'成都金山',
          nodeType:2,//0:人员，1:企业
          related:true,
      },
  },
  {
      data:{
          id:5,
          name:'小米武汉',
          nodeType:2,//0:root,1:人员，2:企业,
          related:true,
      },
  },
  {
      data:{
          id:6,
          name:'小米产业',
          nodeType:2,//0:人员，1:企业
          related:true,
      },
  },
  {
      data:{
          id:7,
          name:'小米科技股份有限公司',
          nodeType:0,
          related:true
      },
  },
  {
      data:{
          id:8,
          name:'林斌',
          nodeType:1,//1:人员，2:企业
          related:true,
      },
  },
  {
      data:{
          id:9,
          name:'重庆小额贷款\n公司',
          nodeType:2,//1:人员，2:企业
          related:true,
      },
  },
  {
      data:{
          id:10,
          name:'北京小米电子软件公司',
          nodeType:2,//1:人员，2:企业
          related:true,
      },
  },
  //线,指向雷军的
  {
      data:{
          id:'1-0',
          lineType:0,//0，董事，1投资
          source:7,
          target:1
      }
  },
  {
      data:{
          id:'1-1',
          lineType:0,
          source:2,
          target:1
      }
  },
  {
      data:{
          id:'1-2',
          source:3,
          lineType:1,
          target:1
      }
  },
  {
      data:{
          id:'1-3',
          lineType:1,
          source:4,
          target:1
      }
  },
  {
      data:{
          id:'1-4',
          source:5,
          lineType:0,
          target:1
      }
  },
  {
      data:{
          id:'1-5',
          source:6,
          lineType:0,
          target:1
      }
  },
  // 指向林斌的
  {
      data:{
          id:'8-1',
          source:7,
          lineType:1,
          target:8
      }
  },
  {
      data:{
          id:'8-2',
          source:9,
          lineType:0,
          target:8
      }
  },
  {
      data:{
          id:'8-3',
          source:10,
          lineType:1,
          target:8
      }
  },
]
